export const quotes = [
"Life is about making an impact, not making an income. –Kevin Kruse",
"Whatever the mind of man can conceive and believe, it can achieve. –Napoleon Hill",
"Strive not to be a success, but rather to be of value. –Albert Einstein",
"I attribute my success to this: I never gave or took any excuse. –Florence Nightingale",
"You miss 100% of the shots you don’t take. –Wayne Gretzky",
"The most difficult thing is the decision to act, the rest is merely tenacity. –Amelia Earhart",
"Every strike brings me closer to the next home run. –Babe Ruth",
"Definiteness of purpose is the starting point of all achievement. –W. Clement Stone",
"Life isn't about getting and having, it's about giving and being. –Kevin Kruse",
"Life is what happens to you while you’re busy making other plans. –John Lennon",
"We become what we think about. –Earl Nightingale",
"Life is 10% what happens to me and 90% of how I react to it. –Charles Swindoll",
"The most common way people give up their power is by thinking they don’t have any. –Alice Walker",
"The mind is everything. What you think you become.  –Buddha",
"The best time to plant a tree was 20 years ago. The second best time is now. –Chinese Proverb",
"An unexamined life is not worth living. –Socrates",
"Eighty percent of success is showing up. –Woody Allen",
"Your time is limited, so don’t waste it living someone else’s life. –Steve Jobs",
"Winning isn’t everything, but wanting to win is. –Vince Lombardi",
"I am not a product of my circumstances. I am a product of my decisions. –Stephen Covey",
"Every child is an artist.  The problem is how to remain an artist once he grows up. –Pablo Picasso",
"You can never cross the ocean until you have the courage to lose sight of the shore. –Christopher Columbus",
"Either you run the day, or the day runs you. –Jim Rohn",
"Whether you think you can or you think you can’t, you’re right. –Henry Ford",
"The two most important days in your life are the day you are born and the day you find out why. –Mark Twain",
"The best revenge is massive success. –Frank Sinatra",
"Life shrinks or expands in proportion to one's courage. –Anais Nin",
"There is only one way to avoid criticism: do nothing, say nothing, and be nothing. –Aristotle",
"The only person you are destined to become is the person you decide to be. –Ralph Waldo Emerson",
"Go confidently in the direction of your dreams.  Live the life you have imagined. –Henry David Thoreau",
"Certain things catch your eye, but pursue only those that capture the heart. – Ancient Indian Proverb",
"Believe you can and you’re halfway there. –Theodore Roosevelt",
"Everything you’ve ever wanted is on the other side of fear. –George Addair",
"Teach thy tongue to say, \"I do not know,\" and thous shalt progress. –Maimonides",
"Start where you are. Use what you have.  Do what you can. –Arthur Ashe",
"Fall seven times and stand up eight. –Japanese Proverb",
"Everything has beauty, but not everyone can see. –Confucius",
"How wonderful it is that nobody need wait a single moment before starting to improve the world. –Anne Frank",
"When I let go of what I am, I become what I might be. –Lao Tzu",
"Happiness is not something readymade.  It comes from your own actions. –Dalai Lama",
"If you're offered a seat on a rocket ship, don't ask what seat! Just get on. –Sheryl Sandberg",
"If the wind will not serve, take to the oars. –Latin Proverb",
"You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground. –Unknown",
"Too many of us are not living our dreams because we are living our fears. –Les Brown",
"Challenges are what make life interesting and overcoming them is what makes life meaningful. –Joshua J. Marine",
"If you want to lift yourself up, lift up someone else. –Booker T. Washington",
"You take your life in your own hands, and what happens? A terrible thing, no one to blame. –Erica Jong",
"I didn’t fail the test. I just found 100 ways to do it wrong. –Benjamin Franklin",
"A person who never made a mistake never tried anything new. – Albert Einstein",
"The person who says it cannot be done should not interrupt the person who is doing it. –Chinese Proverb",
"There are no traffic jams along the extra mile. –Roger Staubach",
"It is never too late to be what you might have been. –George Eliot",
"You become what you believe. –Oprah Winfrey",
"I would rather die of passion than of boredom. –Vincent van Gogh",
"A truly rich man is one whose children run into his arms when his hands are empty. –Unknown",
"Build your own dreams, or someone else will hire you to build theirs. –Farrah Gray",
"Education costs money.  But then so does ignorance. –Sir Claus Moser",
"I have learned over the years that when one's mind is made up, this diminishes fear. –Rosa Parks",
"It does not matter how slowly you go as long as you do not stop. –Confucius",
"Remember that not getting what you want is sometimes a wonderful stroke of luck. –Dalai Lama",
"You can’t use up creativity.  The more you use, the more you have. –Maya Angelou",
"Dream big and dare to fail. –Norman Vaughan",
"Our lives begin to end the day we become silent about things that matter. –Martin Luther King Jr.",
"Do what you can, where you are, with what you have. –Teddy Roosevelt",
"If you do what you’ve always done, you’ll get what you’ve always gotten. –Tony Robbins",
"Dreaming, after all, is a form of planning. –Gloria Steinem",
"You may be disappointed if you fail, but you are doomed if you don't try. –Beverly Sills",
"Remember no one can make you feel inferior without your consent. –Eleanor Roosevelt",
"Life is what we make it, always has been, always will be. –Grandma Moses",
"The question isn’t who is going to let me; it’s who is going to stop me. –Ayn Rand",
"It’s not the years in your life that count. It’s the life in your years. –Abraham Lincoln",
"Change your thoughts and you change your world. –Norman Vincent Peale",
"Either write something worth reading or do something worth writing. –Benjamin Franklin",
"Nothing is impossible, the word itself says, “I’m possible!” –Audrey Hepburn",
"The only way to do great work is to love what you do. –Steve Jobs",
"If you can dream it, you can achieve it. –Zig Ziglar",
"We are what we repeatedly do. Excellence, therefore, is not an act but a habit. –Aristotle",
"The best way out is always through. –Robert Frost",
"Do not wait to strike till the iron is hot; but make it hot by striking. –William B. Sprague",
"Great spirits have always encountered violent opposition from mediocre minds. –Albert Einstein",
"I know for sure that what we dwell on is who we become. –Oprah Winfrey",
"You must be the change you want to see in the world. –Mahatma Gandhi",
"Whatever you do will be insignificant, but it is very important that you do it. –Mahatma Gandhi",
"Failure is the condiment that gives success its flavor. –Truman Capote",
"Vision without action is daydream. Action without vision is nightmare. –Japanese Proverb",
"If you keep saying things are going to be bad, you have a chance of being a prophet. –Isaac B. Singer",
"Success consists of doing the common things of life uncommonly well. –Unknown",
"Losers visualize the penalties of failure. Winners visualize the rewards of success. –Unknown",
"Some succeed because they are destined. Some succeed because they are determined. –Unknown",
"Setting an example is not the main means of influencing others; it is the only means. –Albert Einstein",
"Remember that happiness is a way of travel, not a destination. –Roy Goodman",
"The best way to cheer yourself up is to try to cheer somebody else up. –Mark Twain",
"Age is an issue of mind over matter. If you don’t mind, it doesn’t matter. –Mark Twain",
"Whenever you find yourself on the side of the majority, it’s time to pause and reflect. –Mark Twain",
"The world is more malleable than you think and it’s waiting for you to hammer it into shape. –Bono",
"I can’t understand why people are frightened by new ideas. I’m frightened by old ones. –John Cage",
"The difference between ordinary and extraordinary is that little extra. –Unknown",
"Success is the ability to go from failure to failure without losing your enthusiasm. –Sir Winston Churchill",
"Attitudes are contagious. Make yours worth catching. –Unknown",
"Do not let what you cannot do interfere with what you can do. –John Wooden",
"In matters of style, swim with the current; in matters of principle, stand like a rock. –Thomas Jefferson",
"Talent is formed in solitude, character in the bustle of the world.” –Johann Wolfgang von Goethe",
"If you want to make your dreams come true, the first thing you have to do is wake up. –J.M. Power",
"Sometimes even to live is an act of courage. –Seneca",
"Defeat is not bitter unless you swallow it. –Joe Clark",
"People seem not to see that their opinion of the world is also a confession of character. –Ralph Waldo Emerson",
"If you’re going through hell, keep going. –Winston Churchill",
"Life is a shipwreck but we must not forget to sing in the lifeboats. –Voltaire",
"The secret to life is meaningless unless you discover it yourself. –W. Somerset Maugham",
"Have the passion, take the action & magic will happen. –Bar Rafaeli",
"Keep your face always toward the sunshine—and shadows will fall behind you. –Walt Whitman",
"It is always the simple that produces the marvelous. –Amelia Barr",
"The world is full of magical things patiently waiting for our wits to grow sharper. –Bertrand Russell",
"Let us make our future now, and let us make our dreams tomorrow’s reality. –Malala Yousafzai",
"All you need is the plan, the road map, and the courage to press on to your destination. –Earl Nightingale",
"The glow of one warm thought is to me worth more than money. –Thomas Jefferson",
"The power of imagination makes us infinite. –John Muir",
"Try to be a rainbow in someone’s cloud. –Maya Angelou",
"I believe that if one always looked at the skies, one would end up with wings. –Gustave Flaubert",
"I dwell in possibility. –Emily Dickinson",
"Light tomorrow with today. –Elizabeth Barrett Browning",
"I arise full of eagerness and energy, knowing well what achievement lies ahead of me. –Zane Grey",
"A No. 2 pencil and a dream can take you anywhere. –Joyce Meyer",
"Happiness is not something you postpone for the future; it is something you design for the present. –Jim Rohn",
"In a gentle way, you can shake the world. –Mahatma Gandhi",
"Let your life lightly dance on the edges of time like dew on the tip of a leaf. –Rabindranath Tagore",
"Follow your bliss and the universe will open doors where there were only walls. –Joseph Campbell",
"Each day provides its own gifts. –Marcus Aurelius",
"I believe purpose is something for which one is responsible; it’s not just divinely assigned. –Michael J. Fox",
"The self is made, not given. –Barbara Myerhoff",
"Lean forward into your life. Begin each day as if it were on purpose. –Mary Anne Radmacher",
"There is no greater agony than bearing an untold story inside you. –Maya Angelou",
"Great minds have purposes, others have wishes. –Washington Irving",
"The secret of success is constancy to purpose. –Benjamin Disraeli",
"What am I living for and what am I dying for are the same question. –Margaret Atwood",
"People who use time wisely spend it on activities that advance their overall purpose in life. –John C. Maxwell",
"Our greatest glory is not in never falling, but in rising every time we fall. –Confucius",
"All our dreams can come true, if we have the courage to pursue them. –Walt Disney",
"Hardships often prepare ordinary people for an extraordinary destiny. –C.S. Lewis",
"There is only one thing that makes a dream impossible to achieve: the fear of failure. –Paulo Coelho",
"It’s not whether you get knocked down. It’s whether you get up. –Vince Lombardi",
"Your true success in life begins only when you make the commitment to become excellent at what you do. –Brian Tracy",
"Definiteness of purpose is the starting point of all achievement. –W. Clement Stone",
"Hard times don’t create heroes. It is during the hard times when the ‘hero’ within us is revealed. –Bob Riley",
"Believe you can and you’re halfway there. –Theodore Roosevelt",
"Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change. –Unknown",
"Whatever you hold in your mind on a consistent basis is exactly what you will experience in your life. –Tony Robbins",
"Strength does not come from physical capacity. It comes from an indomitable will. –Mahatma Gandhi",
"Perseverance is the hard work you do after you get tired of doing the hard work you already did. –Newt Gingrich",
"The future belongs to those who believe in the beauty of their dreams. –Franklin D. Roosevelt",
"I am not a product of my circumstances. I am a product of my decisions. –Stephen Covey",
"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.Roy T. Bennett",
"Don’t wish it were easier. Wish you were better. –Jim Rohn",
"It is during our darkest moments that we must focus to see the light. –Aristotle Onassis",
"Fortune always favors the brave, and never helps a man who does not help himself. –P. T. Barnum",
"Go confidently in the direction of your dreams. Live the life you have imagined. –Henry David Thoreau",
"Perfection is not attainable, but if we chase perfection we can catch excellence. –Vince Lombardi",
"If you don’t like something, change it. If you can’t change it, change your attitude. –Maya Angelou",
"Failure will never overtake me if my determination to succeed is strong enough. –Og Mandino",
"Setting goals is the first step into turning the invisible into the visible. –Tony Robbins",
"Only those who dare to fail greatly can ever achieve greatly. –Robert F. Kennedy",
"In order to carry a positive action we must develop here a positive vision. –Dalai Lama",
"Be so happy that when others look at you they become happy too. –Unknown",
"I never dreamed about success. I worked for it. –Estee Lauder",
"There is no greater disability in society than the inability to see a person as more. –Robert M. Hensel",
"The best way to gain self-confidence is to do what you are afraid to do. –Swati Sharma",
"You will never find time for anything. If you want time you must make it. –Charles Buxton",
"Life is not about waiting for the storm to pass but learning to dance in the rain. –Vivian Greene",
"Experience is the teacher of all things. –Julius Caesar"
];